just BIG update

diff --git a/portconf b/portconf
--- a/portconf
+++ b/portconf
@@ -91,38 +91,79 @@ current_profile(){
 MAKE_USES="${USE}"
 unset USE
 [ -z "${PORTDIR}" ] && PORTDIR="/usr/portage"
-[ -n "${PORTDIR_OVERLAY}" ] && PORTDIR="${PORTDIR} ${PORTDIR_OVERLAY}"
+[ -n "${PORTDIR_OVERLAY}" ] && MY_PORTDIR="${PORTDIR} ${PORTDIR_OVERLAY}"
 ############################################################################
 ################ timestamp #################################################
 timestamp(){
 	ls -dgo --time-style=+%s --color=never ${*} 2>/dev/null | awk '{print $4}' | sort | tail -n1
 }
 ############################################################################
+################ repo fix ##################################################
+repo_fix(){
+	if [[ -n "${PORTDIR_OVERLAY}" ]];then
+		export OVERLAY_CACHE_METHOD="parse|ebuild*"
+		for path in ${PORTDIR_OVERLAY};do
+			local_categories="$(ls -1 ${path}/*/*/*.ebuild | sed -e "s|${path}/||g;s|/.*||g" | sort -u)"
+			portage_categoties="$(cat ${PORTDIR}/profiles/categories)"
+			if [[ -n "$(grep -v "${portage_categoties}" <<< "${local_categories}")" ]];then
+				if [[ ! -f "${path}/profiles/categories" ]];then
+					[[ ! -d "${path}/profiles" ]] && mkdir "${path}/profiles" && tmp_categories+=" ${path}/profiles"
+					echo -e "Creating temporary 'categories': ${path}"
+					echo "${local_categories}" >> "${path}/profiles/categories"
+					tmp_categories+=" ${path}/profiles/categories"
+				fi
+			fi
+		done
+	fi
+}
+############################################################################
+################ rm repo fix ###############################################
+rm_repo_fix(){
+	if [[ -n "${tmp_categories}" ]];then
+		for tmp_category in ${tmp_categories};do
+			rm -rf "${tmp_category}"
+		done
+	fi
+}
+############################################################################
 ################ eix check #################################################
 eix_check(){
 	exist="$(eix --version 2>/dev/null)"
 	if [ -n "${exist}" ];then
-		eix_stamp="$(timestamp /var/cache/eix/portage.eix)"
-		for path in ${PORTDIR};do
-			[ -z "${port_stamp}" ] && port_stamp="0"
-			path_stamp="$(timestamp ${path}/{*,*/*})"
-			if (( "${path_stamp}" > "${port_stamp}" ));then
-				port_stamp="${path_stamp}"
-			fi
-		done
-		if (( "${port_stamp}" > "${eix_stamp}" ));then
-			echo -e "eix cache: ${green}updating${restore}"
-			emerge --metadata
-			eix-update
-			eend $? 2>/dev/null
-		else
-			echo -e "eix cache: ${green}already up-to-date${restore}"
-			eend $? 2>/dev/null
-		fi
+		echo -e "${underline}Creating new temporary cache.${restore}"
+		repo_fix
+		eix_cache="$(mktemp)"
+		chown portage:portage "${eix_cache}"
+		export EIX_CACHEFILE="${eix_cache}"
+		eix-update
 	else
 		echo -e "${green}app-portage/eix${restore} ${red}not installed!${restore}"
 		eend 1 2>/dev/null
 		exit 1
+	fi
+	rm_repo_fix
+}
+############################################################################
+################ eix check method ##########################################
+eix_method(){
+	if [[ -z "$(eix --dump | grep '^OVERLAY_CACHE_METHOD="parse|ebuild\*"')" ]];then
+		[[ -n "${yes}" ]] && eix_check
+		echo -ne "\n${red}!default 'OVERLAY_CACHE_METHOD'${restore}${contrast} \
+Create temporary cache?${restore} [${green}Yes${restore}/${red}No${restore}] ";
+		while read x;do
+			case ${x} in
+				Yes | YES | yes | Y | y | "" )
+					eix_check
+					break;;
+				No | NO | no | N | n )
+					repo_fix
+					eix-update
+					rm_repo_fix
+					break;;
+				* ) echo -ne "Sorry, response '${x}' not understood. [${green}Yes${restore}/${red}No${restore}] "
+					continue;;
+			esac
+		done
 	fi
 }
 ############################################################################
@@ -184,13 +225,13 @@ diff_ask(){
 				string="$(sed -e 's|/|\\/|g' -e 's|^+||;s|^-||' -e 's|\*|\\*|g' <<< "${line}")"
 				[[ -n "${string}" ]] && plus="$(cat "${2}" | grep -n "${string}" | cut -d\: -f1 | tr $'\n' " ")" || plus="X"
 				[[ -n "${string}" ]] && minus="$(cat "${1}" | grep -n "${string}" | cut -d\: -f1 | tr $'\n' " ")" || minus="X"
-				for x in ${minus};do
+				[[ "${minus}" != "X" ]] && for x in ${minus};do
 					[[ "$(sed -n "${x}p" ${1})" == "$(sed -n "${x}p" ${2})" ]] &&\
 					minus="${minus//${x}/}" && minus_exist=" == line ${contrast}${x}${restore}"
 				done
 				minus="${minus# }"
 				minus="${minus% }"
-				for z in ${plus};do
+				[[ "${plus}" != "X" ]] && for z in ${plus};do
 					[[ "$(sed -n "${z}p" ${1})" == "$(sed -n "${z}p" ${2})" ]] &&\
 					plus="${plus//${z}/}"  && plus_exist=" == line ${contrast}${x}${restore}"
 				done
@@ -600,7 +641,7 @@ invalid_uses(){
 		for path in ${PORTDIR_OVERLAY};do
 			tput civis
 			echo -e "${underline}Preparing use flags${restore}: ${contrast}${path}${restore}" 2>/dev/null
-			ALL_Q_USE+=" $(PORTDIR="${path}" quse -Ca)"
+			ALL_Q_USE+="$(PORTDIR="${path}" quse -Ca)"$'\n'
 			rm "${path}/.ebuild.x"
 			eend $? 2>/dev/null
 		done 2>/dev/null
@@ -609,6 +650,10 @@ invalid_uses(){
 ############################################################################
 check_uses(){
 	echo -e "${underline}Checking use flags in${restore} ${contrast}${file#${PORT_ETC}/}${restore}:"
+	##### eix env #####
+	export FORMAT='<availableversions:USEONLY>'
+	export USEONLY=' <use>'
+
 	while read category pn ver slot;do
 	#### just count
 		tput sc
@@ -617,48 +662,62 @@ check_uses(){
 		tput rc
 
 		#### broken overlays workaround ####
-		Q_USE+=" $( grep "${category}/${pn}/" <<< "${ALL_Q_USE}" | cut -d" " -f2- | tr -d "+")"
-
-		ALL_USE="$(
-		eix --xml --end "${category}/${pn}"|grep -e iuse -e "use enabled=\"1\"" -e "use enabled=\"0\"" |\
-		sed -e "s|<iuse>||g" -e "s|<use enabled=\"1\">||g" -e "s|<use enabled=\"0\">||g" \
-		-e "s|<iuse default=\"1\">||g" -e "s|</iuse>||g" -e "s|</use>||g"
-		)"
+		Q_USE="$( grep "${category}/${pn}/" <<< "${ALL_Q_USE}" | cut -d" " -f2- | tr "[:space:]" $'\n' | sort -u | sed 's|^+||g')"
+		ALL_USE=" $(eix --end "${category}/${pn}")" || continue
+		ALL_USE="$(sed -e 's|\[.*||g' -e 's| +| |g;s| -| |g' <<< "${ALL_USE}")"
 		ALL_USE="$(echo -e "${ALL_USE}" "${Q_USE}" | tr "[:space:]" $'\n' | sort -u | sed -e '/^$/d')"
 		LOCAL="$(grep "\<${category}/${pn}\> " "${file}" | cut -d" " -f2- | sed -e "s|#.*||g" | tr "[:space:]" $'\n' | sort -u)"
 		USES="$(sed -e 's|^-||g' <<< "${LOCAL}")"
 		for use in ${USES};do
-			if ! grep -q "\<${use}\>" <<< "${ALL_USE}";then
-				grep -q "\<${use}\>" <<< "${incorrect_use}" || incorrect_use="${incorrect_use} ${use}"
+			if ! grep -q "^${use}$" <<< "${ALL_USE}";then
+				grep -q " ${use}\>" <<< "${incorrect_use}" || incorrect_use="${incorrect_use} ${use}"
 			else
 				incorrect_use="${incorrect_use// ${use}/}"
 			fi
 
 			if grep -q "^${use}$" <<< "${GLOBAL}" && grep -q "^${use}$" <<< "${LOCAL}";then
-				incorrect_use="${incorrect_use} ${use}"
+				global_use="${global_use} ${use}"
 			elif grep -q "^\-${use}$" <<< "${GLOBAL}" && grep -q "^\-${use}$" <<< "${LOCAL}";then
-				incorrect_use="${incorrect_use} ${use}"
+				global_use="${global_use} -${use}"
+				incorrect_use="${incorrect_use// ${use}/}"
 			fi
 		done
 
 		incorrect_use="$(echo ${incorrect_use} | tr "[:space:]" $'\n' | sed -e 's|  | |g' -e '/^ $/d' -e '/^$/d' | sort -u)"
+		global_use="$(echo ${global_use} | tr "[:space:]" $'\n' | sed -e 's|  | |g' -e '/^ $/d' -e '/^$/d' | sort -u)"
 		if [ -n "${incorrect_use}" ];then
 			while read trash;do
-				echo -e "Global or invalid use: ${green}${category}/${pn}${restore}: ${red}${trash}${restore}"
+				echo -e "Invalid use: ${green}${category}/${pn}${restore}: ${red}${trash}${restore}"
 				strings="$(grep "^${category}/${pn}[[:space:]].*\<${trash}\>" ${tmp_file})"
 				while read string;do
 					struse="${string#${category}/${pn}}"
 					struse="$(tr "[:space:]" $'\n' <<< ${struse})"
-					usefxd="$(sed -e "s|^${trash}$||" -e "s|^\-${trash}$||" -e '/^$/d' <<< "${struse}")"
+					usefxd="$(sed -e "s|^${trash#-}$||" -e "s|^\-${trash#-}$||" -e '/^$/d' <<< "${struse}")"
 					usefxd="$(tr $'\n' " " <<< "${usefxd}")"
 					usefxd="$(sed -e 's| - | |g' -e 's/[ -]*$//' <<< ${usefxd})"
 					strfxd="${category}/${pn} ${usefxd}"
-					sed -e "s|^${category}/${pn}[[:space:]].*${trash}.*|$strfxd|" -i ${tmp_file} 2>/dev/null
+					sed -e "s|^${category}/${pn}[[:space:]].*${trash#-}.*|$strfxd|" -i ${tmp_file} 2>/dev/null
 					eend $? 2>/dev/null
 				done <<< "${strings}"
 			done <<< "${incorrect_use}"
 		fi
-		unset ALL_USE LOCAL USES incorrect_use use Q_USE
+		if [ -n "${global_use}" ];then
+			while read trash;do
+				echo -e "Global  use: ${green}${category}/${pn}${restore}: ${red}${trash}${restore}"
+				strings="$(grep "^${category}/${pn}[[:space:]].*\<${trash#-}\>" ${tmp_file})"
+				while read string;do
+					struse="${string#${category}/${pn}}"
+					struse="$(tr "[:space:]" $'\n' <<< ${struse})"
+					usefxd="$(sed -e "s|^${trash#-}$||" -e "s|^\-${trash#-}$||" -e '/^$/d' <<< "${struse}")"
+					usefxd="$(tr $'\n' " " <<< "${usefxd}")"
+					usefxd="$(sed -e 's| - | |g' -e 's/[ -]*$//' <<< ${usefxd})"
+					strfxd="${category}/${pn} ${usefxd}"
+					sed -e "s|^${category}/${pn}[[:space:]].*${trash#-}.*|$strfxd|" -i ${tmp_file} 2>/dev/null
+					eend $? 2>/dev/null
+				done <<< "${strings}"
+			done <<< "${global_use}"
+		fi
+		unset ALL_USE LOCAL USES incorrect_use global_use use Q_USE
 	done <<< "`[[ -n "${atoms}" ]] && echo -e "${atoms}"`"
 	while read atom opt;do
 		if [ -n "${atom}" ] && [ -z "${opt}" ];then
@@ -667,7 +726,15 @@ check_uses(){
 			eend $? 2>/dev/null
 		fi
 	done <<< "$([ -n "${IGNORE}" ] && grep -v "${IGNORE}" < "${file}" || cat "${file}")"
+	while read atom opt;do
+		if [ -n "${atom}" ] && [ -z "${opt}" ];then
+			echo -e "Removing atom: ${green}${atom}${restore}"
+			sed -e "s|^${atom} *$||" -e '/^$/d' -i "${tmp_file}" 2>/dev/null
+			eend $? 2>/dev/null
+		fi
+	done <<< "$([ -n "${IGNORE}" ] && grep -v "${IGNORE}" < "${tmp_file}" || cat "${tmp_file}")"
 	eend $? 2>/dev/null
+	unset FORMAT USEONLY
 }
 if [ -f "${PORT_ETC}/package.use" ];then
 	file="${PORT_ETC}/package.use"
@@ -687,6 +754,7 @@ if [ -f "${PORT_ETC}/package.use" ];then
 	tput el;
 	tput cnorm;
 	diff_ask "${file}" "${tmp_file}"
+	[[ ! -s "${file}" ]] && remove_ask "${file}"
 elif [ -d "${PORT_ETC}/package.use" ];then
 	for f in `find ${PORT_ETC}/package.use/ -type f`;do
 		if [[ -s "${f}" ]];then
@@ -706,6 +774,7 @@ elif [ -d "${PORT_ETC}/package.use" ];then
 			check_uses;
 			tput cnorm
 			diff_ask "${file}" "${tmp_file}"
+			[[ ! -s "${file}" ]] && remove_ask "${file}"
 		else
 			echo -e "${underline}Removing empty file${restore} ${contrast}${f}${restore}"
 			rm ${f} 2>/dev/null
@@ -877,6 +946,7 @@ help_pc(){
 echo -e \
 "Usage: portconf [OPTION] [OPTION]…[OPTION]
 available OPTIONS:
+--regen-cache, -rc:          Create and use temporary eix-cache and some fix for overlays. Highly recommend!
 --restore, -r:               Rolling up /etc/portage to one of available states.
 --backup, -b:                Create backup for current /etc/portage state.(enabled in all follow options)
 --sort, -s:                  Sort entries alphabetically.
@@ -906,7 +976,8 @@ OPTIONS must be separated by SPACE."
 [[ -z "${@}" ]] && help_pc
 grep -q -e " \--yes\>" -e " \-y\>" <<< " ${@}" && yes="1"
 grep -q -e " \--pretend\>" -e " \-p\>" <<< " ${@}" && pretend="1"
-opts="$(sed -e 's| --yes\>||g' -e 's| -y\>||g' -e 's| --pretend\>||g' -e 's| -p\>||g' <<< " ${@}")"
+grep -q -e " \--regen-cache\>" -e " \-rc\>" <<< " ${@}" && eix_check || eix_method
+opts="$(sed -e 's| --yes\>||g;s| -y\>||g' -e 's| --pretend\>||g;s| -p\>||g' -e 's| --regen-cache\>||g;s| -rc\>||g' <<< " ${@}")"
 for opt in ${opts};do
 	case "${opt}" in
 	--restore | -r ) restore;;
@@ -918,34 +989,34 @@ for opt in ${opts};do
 		backup;
 		sort_use_file;;
 	--use-invalid | -ui )
-		eix_check;
 		backup;
-		invalid_uses;;
+		invalid_uses
+		[[ -n "${eix_cache}" ]] && rm "${eix_cache}";;
 	--use-make | -um )
 		backup;
 		use_makeconf;;
 	--use-full | -uf )
-		eix_check;
 		backup;
 		sort_use_file;
 		invalid_uses;
-		use_makeconf;;
+		use_makeconf
+		[[ -n "${eix_cache}" ]] && rm "${eix_cache}";;
 	--keywords-sort | -ks )
 		backup;
 		sort_keywords;;
 	--trash | -t )
-		eix_check;
 		backup;
 		not_found;
 		env_not_installed;
-		empty_files;;
+		empty_files
+		[[ -n "${eix_cache}" ]] && rm "${eix_cache}";;
 	--force-trash | -ft )
-		eix_check;
 		backup;
 		not_found;
 		env_not_installed;
 		force_not_installed;
-		empty_files;;
+		empty_files
+		[[ -n "${eix_cache}" ]] && rm "${eix_cache}";;
 	--rm-comments | -c )
 		backup;
 		rm_comments;;
@@ -953,7 +1024,6 @@ for opt in ${opts};do
 		backup;
 		rm_all_comments;;
 	--full | -f )
-		eix_check;
 		backup;
 		sort_uniq_files;
 		not_found;
@@ -962,7 +1032,8 @@ for opt in ${opts};do
 		invalid_uses;
 		use_makeconf;
 		sort_keywords;
-		empty_files;;
+		empty_files
+		[[ -n "${eix_cache}" ]] && rm "${eix_cache}";;
 	--files-2-dirs | -f2d )
 		backup;
 		f_to_d;;
